name: Python venv

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8.5, 3.8.8 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up python${{ matrix.python-version }}
        # https://github.com/marketplace/actions/setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python main.py
